#############################################################################
# Makefile for building: SS2MM
# Generated by qmake (3.0) (Qt 5.0.2) on: Wed May 29 00:49:38 2013
# Project:  SS2MM.pro
# Template: app
# Command: C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/bin/qmake.exe -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug INCLUDEPATH+=C:/Users/zeebok/Desktop LIBS+=-LC:/Users/zeebok/Desktop/build-quazip-Desktop_Qt_5_0_2_MinGW_32bit-Release/release/ LIBS+=-lquazip -o Makefile SS2MM.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: SS2MM.pro ../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/win32-g++/qmake.conf ../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/spec_pre.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/device_config.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/common/shell-unix.conf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/qconfig.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_axbase.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_axserver.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_clucene.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_declarative.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_designer.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_help.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_script.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_v8.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qt_functions.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qt_config.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/win32-g++/qmake.conf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/spec_post.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/default_pre.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/default_pre.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/resolve_config.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/default_post.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qml_debug.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/declarative_debug.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/rtti.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/warn_on.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qt.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/resources.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/moc.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/opengl.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/uic.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/windows.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/testcase_targets.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/exceptions.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/yacc.prf \
		../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/lex.prf \
		SS2MM.pro \
		C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/lib/Qt5Widgets.prl \
		C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/lib/Qt5Gui.prl \
		C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug INCLUDEPATH+=C:/Users/zeebok/Desktop LIBS+=-LC:/Users/zeebok/Desktop/build-quazip-Desktop_Qt_5_0_2_MinGW_32bit-Release/release/ LIBS+=-lquazip -o Makefile SS2MM.pro
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/spec_pre.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/device_config.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/common/shell-unix.conf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/qconfig.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_axbase.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_axcontainer.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_axserver.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_bootstrap.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_clucene.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_core.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_declarative.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_designer.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_designercomponents.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_help.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_multimedia.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_network.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_platformsupport.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qml.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_quick.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_quickparticles.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_script.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_scripttools.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_svg.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_uitools.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_v8.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qt_functions.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qt_config.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/win32-g++/qmake.conf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/spec_post.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/exclusive_builds.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/default_pre.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/default_pre.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/resolve_config.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/default_post.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qml_debug.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/declarative_debug.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/rtti.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/warn_on.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/qt.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/resources.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/moc.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/opengl.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/uic.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/win32/windows.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/testcase_targets.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/exceptions.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/yacc.prf:
../../../Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/mkspecs/features/lex.prf:
SS2MM.pro:
C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/lib/Qt5Widgets.prl:
C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/lib/Qt5Gui.prl:
C:/Users/zeebok/Desktop/qt-everywhere-opensource-src-5.0.2/qtbase/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug INCLUDEPATH+=C:/Users/zeebok/Desktop LIBS+=-LC:/Users/zeebok/Desktop/build-quazip-Desktop_Qt_5_0_2_MinGW_32bit-Release/release/ LIBS+=-lquazip -o Makefile SS2MM.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
